update ghost deployment configs

diff --git a/cluster/apps/ghost/06-ghost-deployment.yaml b/cluster/apps/ghost/06-ghost-deployment.yaml
--- a/cluster/apps/ghost/06-ghost-deployment.yaml
+++ b/cluster/apps/ghost/06-ghost-deployment.yaml
@@ -15,6 +15,14 @@ spec:
   selector:
     matchLabels:
       app: ghost-k8s
+  minReadySeconds: 5
+  strategy:
+    type: RollingUpdate
+    rollingUpdate:
+      maxUnavailable: 0
+      maxSurge: 3
+  revisionHistoryLimit: 4
+  progressDeadlineSeconds: 600
   template:
     metadata:
       namespace: ghost-k8s
@@ -38,84 +46,89 @@ spec:
           sizeLimit: 64Mi
 
       initContainers:
-      - name: ghost-k8s-init
-        image: docker.io/bitnami/git:latest
+      - name: permissions-fix
+        imagePullPolicy: Always
+        image: docker.io/busybox:stable-musl
         env:
         - name: GHOST_INSTALL
-          value: /var/lib/ghost
+          value: /home/nonroot/app/ghost
         - name: GHOST_CONTENT
-          value: /var/lib/ghost/content
+          value: /home/nonroot/app/ghost/content
         - name: NODE_ENV
           value: production
         securityContext:
-          readOnlyRootFilesystem: false
+          readOnlyRootFilesystem: true
           allowPrivilegeEscalation: false
-          runAsNonRoot: false
         resources:
           limits:
-            cpu: 1000m
+            cpu: 900m
             memory: 1000Mi
           requests:
             cpu: 100m
             memory: 128Mi
         command:
-          - /bin/bash
+          - /bin/sh
           - '-c'
           - |
-            set -ex
-            # Check if $GHOST_CONTENT/themes/source exists
-            if [ ! -d "$GHOST_CONTENT/themes/source" ]; then
-              # Clone the repository if the directory doesn't exist
-              git clone https://github.com/TryGhost/Source.git $GHOST_CONTENT/themes/source  --single-branch --branch=main --depth=1
-              echo "Cloned Source theme"
-              # Remove gitconfig file and gitcredentials file.
-              rm -f $GHOST_CONTENT/themes/source/.gitconfig $GHOST_CONTENT/themes/source/.git-credentials || true
-            else
-              # If the directory exists, recursively delete it.
-              rm -rf $GHOST_CONTENT/themes/source
-              # Clone the repository 
-              git clone https://github.com/TryGhost/Source.git $GHOST_CONTENT/themes/source  --single-branch --branch=main --depth=1
-              # Remove gitconfig file and gitcredentials file.
-              rm -f $GHOST_CONTENT/themes/source/.gitconfig $GHOST_CONTENT/themes/source/.git-credentials || true
-            fi
-            if [ ! -d "$GHOST_CONTENT/data" ]; then
-              mkdir "$GHOST_CONTENT/data"
-            fi
-            chown -Rf 1000:1000 $GHOST_CONTENT || true
-            echo "Assured ownership of the ghost installation"
+            set -e
 
+            export DIRS='files logs apps themes data public settings images media'
+            echo 'Check if base dirs exists, if not, create them'
+            echo "Directories to check: $DIRS"
+            for dir in $DIRS; do
+              if [ ! -d $GHOST_CONTENT/$dir ]; then
+                echo "Creating $GHOST_CONTENT/$dir directory"
+                mkdir -pv $GHOST_CONTENT/$dir || echo "Error creating $GHOST_CONTENT/$dir directory"
+              fi
+              chown -Rfv 65532:65532 $GHOST_CONTENT/$dir && echo "chown ok on $dir" || echo "Error changing ownership of $GHOST_CONTENT/$dir directory"
+            done
             exit 0
 
         volumeMounts:
         - name: ghost-k8s-static-ghost
-          mountPath: /var/lib/ghost/content
+          mountPath: /home/nonroot/app/ghost/content
           readOnly: false
 
       containers:
       - name: ghost-k8s
-        image: ghcr.io/sredevopsorg/ghost-on-kubernetes:v5.101.1
+        image: ghcr.io/sredevopsorg/ghost-on-kubernetes:v5.130.4
         imagePullPolicy: Always
         ports:
-        - name: ghk3s
+        - name: ghk8s
           containerPort: 2368
           protocol: TCP
 
         # You should uncomment the following lines in production. Change the values according to your environment.
 
-        livenessProbe:
+        readinessProbe:
           httpGet:
             path: /ghost/api/v4/admin/site/
-            port: ghk3s
+            port: ghk8s
             httpHeaders:
             - name: X-Forwarded-Proto
               value: https
             - name: Host
               value: blog.gustend.net
-          periodSeconds: 3600
+          periodSeconds: 10
+          timeoutSeconds: 3
+          successThreshold: 1
+          failureThreshold: 3
+          initialDelaySeconds: 10
+
+        livenessProbe:
+          httpGet:
+            path: /ghost/api/v4/admin/site/
+            port: ghk8s
+            httpHeaders:
+            - name: X-Forwarded-Proto
+              value: https
+            - name: Host
+              value: blog.gustend.net
+          periodSeconds: 300
           timeoutSeconds: 3
           successThreshold: 1
           failureThreshold: 1
-          initialDelaySeconds: 60
+          initialDelaySeconds: 30
 
         env:
         - name: NODE_ENV
@@ -130,10 +143,10 @@ spec:
 
         volumeMounts:
         - name: ghost-k8s-static-ghost
-          mountPath: /var/lib/ghost/content
+          mountPath: /home/nonroot/app/ghost/content
         - name: ghost-config-prod
           readOnly: true
-          mountPath: /var/lib/ghost/config.production.json
+          mountPath: /home/nonroot/app/ghost/config.production.json
           subPath: config.production.json
         - name: tmp # This is the temporary volume mount to allow loading themes
           mountPath: /tmp
@@ -142,7 +155,7 @@ spec:
           readOnlyRootFilesystem: true
           allowPrivilegeEscalation: false
           runAsNonRoot: true
-          runAsUser: 1000
+          runAsUser: 65532
 
       restartPolicy: Always
       terminationGracePeriodSeconds: 15
@@ -161,7 +174,3 @@ spec:
 
       securityContext: {}
       schedulerName: default-scheduler
-  strategy:
-    type: Recreate
-  revisionHistoryLimit: 2
-  progressDeadlineSeconds: 600
